### ISSUE TITLE
Unable to use with docker-machine

### ISSUE THREAD

**Issue by Dohbedoh** [ChessCorp/docker-ascii-map#10] opened 2016-11-03 23:03 UTC
While I could install docker-ascii-map properly, I am not able to use with **docker-machine**. I see the following error:

```
File "/usr/local/lib/python3.5/site-packages/docker/transport/unixconn.py", line 33, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory
```

Most likely `docker-py`'s client is connecting to the docker.sock by default. 

In the case of docker-machine, the docker host is provided via environment variables. `docker-py` has a solution for that: https://docker-py.readthedocs.io/en/latest/machine/

**Comment by alcibiade** [comment] 2016-11-04 17:05
I have a committed a fix. I'll test it further this weekend and if it is ok, I'll release it as 1.4.2 or 1.5.0

**Comment by alcibiade** [comment] 2016-11-05 10:40
@Dohbedoh could you test with version 0.4.2 to see if the issue is resolved ?

**Comment by Dohbedoh** [comment] 2016-11-05 12:52
LGTM 👍. Tested with 

> docker-machine version 0.8.1, build 41b3b25

**Comment by alcibiade** [comment] 2016-11-06 09:56
Thanks !

**Closed by alcibiade** 2016-11-06 09:56 UTC
Labels: bug, in progress
